version: "3.8"
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - todo_nw

networks:
  todo_nw:
    external: true
