// Package todo provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package todo

import (
	"time"
)

// Error400 defines model for Error400.
type Error400 struct {
	Message *string `json:"message,omitempty"`
}

// Todo defines model for Todo.
type Todo struct {
	Completed  *bool      `json:"completed,omitempty"`
	CreatedAt  *time.Time `json:"created_at,omitempty"`
	Deadline   *time.Time `json:"deadline,omitempty"`
	DeleteFlag *bool      `json:"delete_flag,omitempty"`
	Id         int64      `json:"id"`
	Title      *string    `json:"title,omitempty"`
	UpdatedAt  *time.Time `json:"updated_at,omitempty"`
}

// PostTodosJSONRequestBody defines body for PostTodos for application/json ContentType.
type PostTodosJSONRequestBody = Todo

// PatchTodosIdJSONRequestBody defines body for PatchTodosId for application/json ContentType.
type PatchTodosIdJSONRequestBody = Todo
